data_dir = "/var/lib/vector"

[sources.validator_access_logs]
type = "file"
include = ["/usr/local/openresty/nginx/logs/protection-validator-vector.access.log"]
ignore_older = 86400  # 1 day

[sources.validator_stress_access_logs]
type = "file"
include = ["/usr/local/openresty/nginx/logs/protection-validator-vector-stress.access.log"]
ignore_older = 86400  # 1 day

[transforms.parse_json]
inputs = ["validator_access_logs"]
type = "remap"
source = '''
. = parse_json!(.message, max_depth: 1)
if is_nullish(.site_key) { .site_key = "00000000-0000-0000-0000-000000000000" }
if is_nullish(.server_key) { .server_key = "00000000-0000-0000-0000-000000000000" }
if is_nullish(.project_id) { .project_id = "00000000-0000-0000-0000-000000000000" }
if is_nullish(.customer_id) { .customer_id = "00000000-0000-0000-0000-000000000000" }
if is_nullish(.server_port) { .server_port = 0 }
if !is_timestamp(.created_at) { .created_at = to_unix_timestamp(now(), unit: "milliseconds") }
.remote_addr = ipv6_to_ipv4(.remote_addr) ?? replace(".remote_addr", r'.*:', "")
'''

[transforms.parse_json_stress]
inputs = ["validator_stress_access_logs"]
type = "remap"
source = '''
. = parse_json!(.message, max_depth: 1)
.created_at = now()
if is_nullish(.site_key) { .site_key = "00000000-0000-0000-0000-000000000000" }
if is_nullish(.server_key) { .server_key = "00000000-0000-0000-0000-000000000000" }
if is_nullish(.project_id) { .project_id = "00000000-0000-0000-0000-000000000000" }
if is_nullish(.customer_id) { .customer_id = "00000000-0000-0000-0000-000000000000" }
if is_nullish(.server_port) { .server_port = 0 }
'''

[sinks.click_house]
type = "clickhouse"
inputs = ["parse_json"]
encoding.timestamp_format = "unix"
endpoint = "http://clickhouse:8123"
database = "protection"
table = "requests"
skip_unknown_fields = true
auth = { strategy = "basic", password = "${CLICKHOUSE_PASSWORD}", user = "${CLICKHOUSE_USER}" }

[sinks.click_house_stress]
type = "clickhouse"
inputs = ["parse_json_stress"]
encoding.timestamp_format = "unix"
endpoint = "http://clickhouse:8123"
database = "protection"
table = "stress_requests"
skip_unknown_fields = true
auth = { strategy = "basic", password = "${CLICKHOUSE_PASSWORD}", user = "${CLICKHOUSE_USER}" }

#[sinks.console]
#inputs = ["parse_json"]
#type = "console"
#encoding.codec = "json"
