data_dir = "/var/lib/vector"

[sources.validator_access_logs]
type = "file"
include = ["/usr/local/openresty/nginx/logs/protection-validator-vector.access.log"]
ignore_older = 86400          # 1 day

[transforms.parse_json]
inputs = ["validator_access_logs"]
type = "remap"
source = '''
. = parse_json!(.message, max_depth: 1)
if is_empty(to_string(.site_key) ?? "") { .site_key = "00000000-0000-0000-0000-000000000000" }
if is_empty(to_string(.server_key) ?? "") { .site_key = "00000000-0000-0000-0000-000000000000" }
if is_empty(to_string(.project_id) ?? "") { .site_key = "00000000-0000-0000-0000-000000000000" }
if is_empty(to_string(.customer_id) ?? "") { .site_key = "00000000-0000-0000-0000-000000000000" }
'''

[sinks.click_house]
type = "clickhouse"
inputs = ["parse_json"]
encoding.timestamp_format = "unix"
endpoint = "http://clickhouse:8123"
database = "protection"
table = "requests"
skip_unknown_fields = true

[sinks.click_house.auth]
strategy = "basic"
password = "${CLICKHOUSE_PASSWORD}"
user = "${CLICKHOUSE_USER}"

#[sinks.console]
#inputs = ["parse_json"]
#type = "console"
#encoding.codec = "json"
